/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIReply: typeof import('./src/components/AI/AIReply.vue')['default']
    PopularDestinationsCard: typeof import('./src/components/Home/PopularDestinationsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareTourTraceCard: typeof import('./src/components/Home/ShareTourTraceCard.vue')['default']
    Start: typeof import('./src/components/Assistant/Start.vue')['default']
    TabBar: typeof import('./src/components/Home/TabBar.vue')['default']
    Test: typeof import('./src/components/Home/test.vue')['default']
    UserQuery: typeof import('./src/components/AI/UserQuery.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
